### ISSUE TITLE
preprocessing.py for the skoda dataset fails with TypeError

### ISSUE THREAD

**Issue by nobuyukioishi** [STRCSussex-UbiCompSiegen/dl_har_public#6]
**Describe the bug**
When I execute `python preprocessing.py -d skoda_split`, it fails during the process. Is there anything that I'm missing?

**To Reproduce**

1. Clone this repository
2. install modules in requirements.txt with pip
3. Go to 'dl_har_dataloader/'
4. Execute 'python preprocessing.py -d skoda_split' in the directory.
5. See error

**Expected behavior**
Preprocessed npz files to be generated in data folder under the project's root directory (dl_har_public). 

**Screenshots**
Full output:
```
$ python preprocessing.py -d skoda_split
... dataset path ../data/raw/skodaminicp_2015_08.zip not found
Attempting to download ...
... downloading data from http://har-dataset.org/lib/exe/fetch.php?media=wiki:dataset:skodaminicp:skodaminicp_2015_08.zip
100% |#######################################################################################################################################################################################################################|
Traceback (most recent call last):
  File "preprocessing.py", line 234, in <module>
    preprocess_dataset(loader, args)
  File "preprocessing.py", line 191, in preprocess_dataset
    data_x, data_y, _ = iter_files(dataset, zf, split)
  File "preprocessing.py", line 111, in iter_files
    files = dataset.data_files[user]
TypeError: list indices must be integers or slices, not str
```

**Desktop (please complete the following information):**
 - OS:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

**Additional context**

**Comment by PellattLlo** [comment]
Thanks Nobu, fixed in [257b06b](https://github.com/STRCSussex-UbiCompSiegen/dl_har_public/commit/257b06bee9215d73d98762560e509a8d5c6a8e54)
